export interface SuburbData {
  name: string
  postcode: string
  blurb: string
  testimonial: { name: string; quote: string }
}

export const suburbs: Record<string, SuburbData> = {
  'truganina': {
    name: 'Truganina',
    postcode: '3029',
    blurb: 'Truganina is one of Melbourne\'s fastest-growing suburbs, with many new homes and young families. UDAY Cleaning provides professional residential, commercial, and end of lease cleaning services throughout Truganina. Whether you\'re moving in, moving out, or just need a regular clean, we\'re here to help.',
    testimonial: { name: 'Anna K.', quote: 'The deep clean they did before Christmas was outstanding. Even the oven looked brand new. Absolutely brilliant service in Truganina!' },
  },
  'hoppers-crossing': {
    name: 'Hoppers Crossing',
    postcode: '3029',
    blurb: 'Hoppers Crossing is a well-established suburb in Melbourne\'s west. Our professional cleaning team services homes and businesses throughout Hoppers Crossing with the same care and attention to detail we bring to every job.',
    testimonial: { name: 'Michael T.', quote: 'Regular fortnightly clean and they never miss a spot. Reliable and always on time. Best cleaners in Hoppers Crossing!' },
  },
  'werribee': {
    name: 'Werribee',
    postcode: '3030',
    blurb: 'Werribee is a major hub in Melbourne\'s outer west with a mix of residential and commercial properties. We\'ve been serving the Werribee community for over a decade, providing trusted cleaning services for families and businesses alike.',
    testimonial: { name: 'Emily R.', quote: 'I love that they use eco-friendly products. Safe for my kids and pets. The best cleaning service in Werribee by far!' },
  },
  'tarneit': {
    name: 'Tarneit',
    postcode: '3029',
    blurb: 'Tarneit is a booming suburb in Melbourne\'s west with many new residential estates. Our professional cleaners are fully equipped to handle everything from new-build post-construction cleans to regular home maintenance in Tarneit.',
    testimonial: { name: 'Sarah M.', quote: 'Amazing service! Got our full bond back with no issues. The team was punctual and thorough. Highly recommend in Tarneit!' },
  },
  'point-cook': {
    name: 'Point Cook',
    postcode: '3030',
    blurb: 'Point Cook is a popular family suburb on Melbourne\'s Werribee coast. UDAY Cleaning serves the Point Cook community with professional residential cleaning, end of lease cleaning, and commercial services.',
    testimonial: { name: 'James L.', quote: 'Used UDAY for our end of lease clean and got our full bond back first try. Incredible attention to detail in Point Cook!' },
  },
  'laverton': {
    name: 'Laverton',
    postcode: '3028',
    blurb: 'Laverton is a convenient suburb close to the city and the Western Ring Road. Our team regularly services homes and offices in Laverton with professional, reliable cleaning you can count on.',
    testimonial: { name: 'David W.', quote: 'Professional and thorough. Our office has never looked better. Great service in Laverton!' },
  },
  'altona-meadows': {
    name: 'Altona Meadows',
    postcode: '3028',
    blurb: 'Altona Meadows is a suburban area in Melbourne\'s west with a strong community feel. We provide residential and commercial cleaning services throughout Altona Meadows with our signature eco-friendly approach.',
    testimonial: { name: 'Lisa P.', quote: 'Same-day booking was a lifesaver. They arrived within 2 hours and left the place spotless. Amazing service in Altona Meadows!' },
  },
  'williams-landing': {
    name: 'Williams Landing',
    postcode: '3027',
    blurb: 'Williams Landing is a modern suburb centred around the Williams Landing town centre. Our professional cleaning team serves the Williams Landing community with residential, commercial, and end of lease cleaning.',
    testimonial: { name: 'Tom B.', quote: 'Got my bond back both times using UDAY. The checklist they follow is incredibly thorough. Couldn\'t recommend more for Williams Landing!' },
  },
  'aintree': {
    name: 'Aintree',
    postcode: '3336',
    blurb: 'Aintree is a newer estate suburb within the Rockbank growth corridor, part of the master-planned Grange community. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Aintree, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Priya S.', quote: 'Our regular clean is spot-on every single time — Aintree is lucky to have a team this reliable.' },
  },
  'deanside': {
    name: 'Deanside',
    postcode: '3336',
    blurb: 'Deanside is UDAY Cleaning\'s home suburb — we\'re literally around the corner, so scheduling and same-day availability here is at its best. Our fully insured team services Deanside regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Ahmed K.', quote: 'Our regular clean is spot-on every single time — Deanside is lucky to have a team this reliable.' },
  },
  'fraser-rise': {
    name: 'Fraser Rise',
    postcode: '3336',
    blurb: 'As a new suburb near the Grand Central precinct and Watergardens, popular with young families moving into brand-new builds, Fraser Rise is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Sophie N.', quote: 'Got our full bond back thanks to their end of lease clean in Fraser Rise. Every corner was spotless.' },
  },
  'bonnie-brook': {
    name: 'Bonnie Brook',
    postcode: '3335',
    blurb: 'Bonnie Brook is part of the Rockbank growth corridor near the Bonnie Brook wetlands, with plenty of new-build homes needing their first professional clean, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Bonnie Brook properties.',
    testimonial: { name: 'Daniel C.', quote: 'Our regular clean is spot-on every single time — Bonnie Brook is lucky to have a team this reliable.' },
  },
  'rockbank': {
    name: 'Rockbank',
    postcode: '3335',
    blurb: 'Rockbank is a historic township turned booming growth suburb, serviced by Rockbank railway station and surrounded by new housing estates. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Rockbank, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Grace O.', quote: 'The deep clean before we moved in was incredible — every room in our Rockbank home felt brand new.' },
  },
  'grangefields': {
    name: 'Grangefields',
    postcode: '3335',
    blurb: 'Grangefields is one of the newer estates within The Grange masterplanned community near Rockbank. Our fully insured team services Grangefields regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Rohan P.', quote: 'Our regular clean is spot-on every single time — Grangefields is lucky to have a team this reliable.' },
  },
  'thornhill-park': {
    name: 'Thornhill Park',
    postcode: '3335',
    blurb: 'As a growth-corridor suburb close to the Western Freeway, with a steady stream of new-build handovers needing a thorough first clean, Thornhill Park is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Chloe W.', quote: 'Got our full bond back thanks to their end of lease clean in Thornhill Park. Every corner was spotless.' },
  },
  'fieldstone': {
    name: 'Fieldstone',
    postcode: '3024',
    blurb: 'Fieldstone is a newer estate in the Mount Cottrell growth corridor southwest of Rockbank, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Fieldstone properties.',
    testimonial: { name: 'Mark D.', quote: 'Our regular clean is spot-on every single time — Fieldstone is lucky to have a team this reliable.' },
  },
  'cobblebank': {
    name: 'Cobblebank',
    postcode: '3338',
    blurb: 'Cobblebank is a fast-growing suburb centred around Cobblebank railway station in the Melton growth corridor. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Cobblebank, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Aisha R.', quote: 'Our regular clean is spot-on every single time — Cobblebank is lucky to have a team this reliable.' },
  },
  'strathtulloh': {
    name: 'Strathtulloh',
    postcode: '3338',
    blurb: 'Strathtulloh is one of Melton\'s newest suburbs, with new housing estates going up west of Cobblebank. Our fully insured team services Strathtulloh regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Ben H.', quote: 'Got our full bond back thanks to their end of lease clean in Strathtulloh. Every corner was spotless.' },
  },
  'burnside-heights': {
    name: 'Burnside Heights',
    postcode: '3023',
    blurb: 'As an established residential suburb next to Burnside and Caroline Springs, Burnside Heights is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Natalie F.', quote: 'Our office in Burnside Heights has never looked better. Professional team, always on schedule.' },
  },
  'brookfield': {
    name: 'Brookfield',
    postcode: '3338',
    blurb: 'Brookfield is a growing residential pocket south of Melton township, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Brookfield properties.',
    testimonial: { name: 'Josh T.', quote: 'Our regular clean is spot-on every single time — Brookfield is lucky to have a team this reliable.' },
  },
  'exford': {
    name: 'Exford',
    postcode: '3338',
    blurb: 'Exford is a semi-rural residential area near Melton with larger blocks and acreage properties. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Exford, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Meera V.', quote: 'The deep clean before we moved in was incredible — every room in our Exford home felt brand new.' },
  },
  'eynesbury': {
    name: 'Eynesbury',
    postcode: '3338',
    blurb: 'Eynesbury is a master-planned community near Melton built around a heritage homestead and golf course. Our fully insured team services Eynesbury regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Liam O.', quote: 'Our regular clean is spot-on every single time — Eynesbury is lucky to have a team this reliable.' },
  },
  'melton-south': {
    name: 'Melton South',
    postcode: '3338',
    blurb: 'As an established residential suburb forming the southern half of the Melton township, Melton South is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Jade C.', quote: 'Our regular clean is spot-on every single time — Melton South is lucky to have a team this reliable.' },
  },
  'weir-views': {
    name: 'Weir Views',
    postcode: '3338',
    blurb: 'Weir Views is a newer suburb near Melton, close to the Melton Reservoir, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Weir Views properties.',
    testimonial: { name: 'Vikram S.', quote: 'Got our full bond back thanks to their end of lease clean in Weir Views. Every corner was spotless.' },
  },
  'keilor-downs': {
    name: 'Keilor Downs',
    postcode: '3038',
    blurb: 'Keilor Downs is an established suburb centred around Keilor Downs Village shopping centre. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Keilor Downs, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Ella M.', quote: 'Our office in Keilor Downs has never looked better. Professional team, always on schedule.' },
  },
  'keilor-lodge': {
    name: 'Keilor Lodge',
    postcode: '3038',
    blurb: 'Keilor Lodge is a smaller, semi-rural residential pocket next to Keilor Downs. Our fully insured team services Keilor Lodge regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Connor B.', quote: 'Our regular clean is spot-on every single time — Keilor Lodge is lucky to have a team this reliable.' },
  },
  'taylors-lakes': {
    name: 'Taylors Lakes',
    postcode: '3038',
    blurb: 'As a well-established family suburb around Taylors Lakes Village, Taylors Lakes is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Simran K.', quote: 'The deep clean before we moved in was incredible — every room in our Taylors Lakes home felt brand new.' },
  },
  'watergardens': {
    name: 'Watergardens',
    postcode: '3038',
    blurb: 'Watergardens is the suburb built around Watergardens Town Centre and train station, one of the west\'s biggest shopping hubs, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Watergardens properties.',
    testimonial: { name: 'Tyler G.', quote: 'Our office in Watergardens has never looked better. Professional team, always on schedule.' },
  },
  'diggers-rest': {
    name: 'Diggers Rest',
    postcode: '3427',
    blurb: 'Diggers Rest is a historic railway township on Melbourne\'s outer north-western fringe. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Diggers Rest, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Fatima A.', quote: 'Our regular clean is spot-on every single time — Diggers Rest is lucky to have a team this reliable.' },
  },
  'calder-park': {
    name: 'Calder Park',
    postcode: '3037',
    blurb: 'Calder Park is a residential suburb best known for Calder Park Raceway. Our fully insured team services Calder Park regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Ryan P.', quote: 'Our regular clean is spot-on every single time — Calder Park is lucky to have a team this reliable.' },
  },
  'delahey': {
    name: 'Delahey',
    postcode: '3037',
    blurb: 'As an established family suburb centred on the Delahey Community Centre, Delahey is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Ngozi E.', quote: 'Our regular clean is spot-on every single time — Delahey is lucky to have a team this reliable.' },
  },
  'hillside': {
    name: 'Hillside',
    postcode: '3037',
    blurb: 'Hillside is a well-established residential suburb near Watergardens, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Hillside properties.',
    testimonial: { name: 'Hayley B.', quote: 'Got our full bond back thanks to their end of lease clean in Hillside. Every corner was spotless.' },
  },
  'sydenham': {
    name: 'Sydenham',
    postcode: '3037',
    blurb: 'Sydenham is a suburb built around Sydenham railway station, one of the west\'s major regional rail hubs. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Sydenham, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Arjun M.', quote: 'Our office in Sydenham has never looked better. Professional team, always on schedule.' },
  },
  'taylors-hill': {
    name: 'Taylors Hill',
    postcode: '3037',
    blurb: 'Taylors Hill is an established suburb near Caroline Springs, centred around Taylors Hill Village. Our fully insured team services Taylors Hill regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Zoe L.', quote: 'The deep clean before we moved in was incredible — every room in our Taylors Hill home felt brand new.' },
  },
  'kurunjang': {
    name: 'Kurunjang',
    postcode: '3337',
    blurb: 'As an established residential pocket within Melton, Kurunjang is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Dylan S.', quote: 'Our regular clean is spot-on every single time — Kurunjang is lucky to have a team this reliable.' },
  },
  'melton': {
    name: 'Melton',
    postcode: '3337',
    blurb: 'Melton is the major regional town centre of Melbourne\'s outer west, with its own shopping and civic precinct, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Melton properties.',
    testimonial: { name: 'Nadia H.', quote: 'Our office in Melton has never looked better. Professional team, always on schedule.' },
  },
  'melton-west': {
    name: 'Melton West',
    postcode: '3337',
    blurb: 'Melton West is the residential area west of Melton\'s town centre. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Melton West, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Callum R.', quote: 'Our regular clean is spot-on every single time — Melton West is lucky to have a team this reliable.' },
  },
  'burnside': {
    name: 'Burnside',
    postcode: '3023',
    blurb: 'Burnside is a well-established master-planned suburb neighbouring Caroline Springs. Our fully insured team services Burnside regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Priyanka D.', quote: 'Our regular clean is spot-on every single time — Burnside is lucky to have a team this reliable.' },
  },
  'cairnlea': {
    name: 'Cairnlea',
    postcode: '3023',
    blurb: 'As a master-planned suburb built around Cairnlea Park and its lake, Cairnlea is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Owen F.', quote: 'The deep clean before we moved in was incredible — every room in our Cairnlea home felt brand new.' },
  },
  'caroline-springs': {
    name: 'Caroline Springs',
    postcode: '3023',
    blurb: 'Caroline Springs is a major master-planned suburb centred on Caroline Springs Town Centre and its lake precinct, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Caroline Springs properties.',
    testimonial: { name: 'Bianca T.', quote: 'Our office in Caroline Springs has never looked better. Professional team, always on schedule.' },
  },
  'deer-park': {
    name: 'Deer Park',
    postcode: '3023',
    blurb: 'Deer Park is an established suburb with its own shopping centre and train station. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Deer Park, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Harjot S.', quote: 'Our regular clean is spot-on every single time — Deer Park is lucky to have a team this reliable.' },
  },
  'ravenhall': {
    name: 'Ravenhall',
    postcode: '3023',
    blurb: 'Ravenhall is a fast-growing suburb with plenty of new housing estates. Our fully insured team services Ravenhall regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Megan R.', quote: 'Got our full bond back thanks to their end of lease clean in Ravenhall. Every corner was spotless.' },
  },
  'albanvale': {
    name: 'Albanvale',
    postcode: '3021',
    blurb: 'As an established, multicultural residential suburb near St Albans, Albanvale is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Wei C.', quote: 'Our regular clean is spot-on every single time — Albanvale is lucky to have a team this reliable.' },
  },
  'kealba': {
    name: 'Kealba',
    postcode: '3021',
    blurb: 'Kealba is a small, established residential suburb near Keilor and St Albans, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Kealba properties.',
    testimonial: { name: 'Isabella G.', quote: 'Our regular clean is spot-on every single time — Kealba is lucky to have a team this reliable.' },
  },
  'kings-park': {
    name: 'Kings Park',
    postcode: '3021',
    blurb: 'Kings Park is an established residential suburb in Melbourne\'s western suburbs. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Kings Park, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Noah K.', quote: 'Our regular clean is spot-on every single time — Kings Park is lucky to have a team this reliable.' },
  },
  'st-albans': {
    name: 'St Albans',
    postcode: '3021',
    blurb: 'St Albans is one of the west\'s major hubs, known for its vibrant Main Road East shopping strip and train station. Our fully insured team services St Albans regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Amrita B.', quote: 'Our office in St Albans has never looked better. Professional team, always on schedule.' },
  },
  'harkness': {
    name: 'Harkness',
    postcode: '3337',
    blurb: 'As one of Melton\'s newest master-planned communities, Harkness is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Cody W.', quote: 'Got our full bond back thanks to their end of lease clean in Harkness. Every corner was spotless.' },
  },
  'keilor': {
    name: 'Keilor',
    postcode: '3036',
    blurb: 'Keilor is a historic riverside village on the Maribyrnong River, one of Melbourne\'s oldest settlements, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Keilor properties.',
    testimonial: { name: 'Leah N.', quote: 'The deep clean before we moved in was incredible — every room in our Keilor home felt brand new.' },
  },
  'keilor-north': {
    name: 'Keilor North',
    postcode: '3036',
    blurb: 'Keilor North is a residential suburb just north of the historic Keilor village. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Keilor North, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Farid H.', quote: 'Our regular clean is spot-on every single time — Keilor North is lucky to have a team this reliable.' },
  },
  'ardeer': {
    name: 'Ardeer',
    postcode: '3022',
    blurb: 'Ardeer is a small, established suburb with its own train station. Our fully insured team services Ardeer regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Kayla J.', quote: 'Our regular clean is spot-on every single time — Ardeer is lucky to have a team this reliable.' },
  },
  'laverton-north': {
    name: 'Laverton North',
    postcode: '3026',
    blurb: 'As a mixed industrial and residential suburb in Melbourne\'s west, Laverton North is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Xavier L.', quote: 'Our office in Laverton North has never looked better. Professional team, always on schedule.' },
  },
  'albion': {
    name: 'Albion',
    postcode: '3020',
    blurb: 'Albion is a suburb built around Albion railway station, close to Sunshine, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Albion properties.',
    testimonial: { name: 'Ruby P.', quote: 'Our regular clean is spot-on every single time — Albion is lucky to have a team this reliable.' },
  },
  'glengala': {
    name: 'Glengala',
    postcode: '3020',
    blurb: 'Glengala is a residential locality within the Sunshine West area. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Glengala, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Manpreet K.', quote: 'Our regular clean is spot-on every single time — Glengala is lucky to have a team this reliable.' },
  },
  'sunshine': {
    name: 'Sunshine',
    postcode: '3020',
    blurb: 'Sunshine is a major regional hub with Sunshine Hospital, Sunshine Marketplace and its own train station. Our fully insured team services Sunshine regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Georgia S.', quote: 'Our office in Sunshine has never looked better. Professional team, always on schedule.' },
  },
  'sunshine-north': {
    name: 'Sunshine North',
    postcode: '3020',
    blurb: 'As an established residential suburb north of the Sunshine town centre, Sunshine North is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Kofi A.', quote: 'Our regular clean is spot-on every single time — Sunshine North is lucky to have a team this reliable.' },
  },
  'sunshine-west': {
    name: 'Sunshine West',
    postcode: '3020',
    blurb: 'Sunshine West is an established residential suburb with its own local shops, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Sunshine West properties.',
    testimonial: { name: 'Paige M.', quote: 'Got our full bond back thanks to their end of lease clean in Sunshine West. Every corner was spotless.' },
  },
  'keilor-east': {
    name: 'Keilor East',
    postcode: '3033',
    blurb: 'Keilor East is a leafy, established suburb along the Maribyrnong River. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Keilor East, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Andre F.', quote: 'The deep clean before we moved in was incredible — every room in our Keilor East home felt brand new.' },
  },
  'airport-west': {
    name: 'Airport West',
    postcode: '3042',
    blurb: 'Airport West is a suburb best known for the Airport West Shopping Centre near Melbourne Airport. Our fully insured team services Airport West regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Tahlia B.', quote: 'Our office in Airport West has never looked better. Professional team, always on schedule.' },
  },
  'keilor-park': {
    name: 'Keilor Park',
    postcode: '3042',
    blurb: 'As an established residential suburb near Keilor East, Keilor Park is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Yusuf R.', quote: 'Our regular clean is spot-on every single time — Keilor Park is lucky to have a team this reliable.' },
  },
  'niddrie': {
    name: 'Niddrie',
    postcode: '3042',
    blurb: 'Niddrie is a leafy suburb with the Keilor Road shopping strip nearby, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Niddrie properties.',
    testimonial: { name: 'Sienna C.', quote: 'Our regular clean is spot-on every single time — Niddrie is lucky to have a team this reliable.' },
  },
  'avondale-heights': {
    name: 'Avondale Heights',
    postcode: '3034',
    blurb: 'Avondale Heights is an established suburb set along the Maribyrnong River. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Avondale Heights, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Hamish D.', quote: 'The deep clean before we moved in was incredible — every room in our Avondale Heights home felt brand new.' },
  },
  'sunbury': {
    name: 'Sunbury',
    postcode: '3429',
    blurb: 'Sunbury is a historic outer township on Jacksons Creek with its own town centre, Sunbury Square. Our fully insured team services Sunbury regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Tanvi P.', quote: 'Our regular clean is spot-on every single time — Sunbury is lucky to have a team this reliable.' },
  },
  'braybrook': {
    name: 'Braybrook',
    postcode: '3019',
    blurb: 'As an established, multicultural suburb near the Maribyrnong River, Braybrook is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Cooper G.', quote: 'Our regular clean is spot-on every single time — Braybrook is lucky to have a team this reliable.' },
  },
  'manor-lakes': {
    name: 'Manor Lakes',
    postcode: '3024',
    blurb: 'Manor Lakes is a master-planned community within Wyndham Vale, centred around Manor Lakes Central, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Manor Lakes properties.',
    testimonial: { name: 'Amara O.', quote: 'Got our full bond back thanks to their end of lease clean in Manor Lakes. Every corner was spotless.' },
  },
  'bulla': {
    name: 'Bulla',
    postcode: '3428',
    blurb: 'Bulla is a small historic township on the Maribyrnong River. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Bulla, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Blake T.', quote: 'Our regular clean is spot-on every single time — Bulla is lucky to have a team this reliable.' },
  },
  'brooklyn': {
    name: 'Brooklyn',
    postcode: '3012',
    blurb: 'Brooklyn is a small residential pocket bordering industrial Melbourne. Our fully insured team services Brooklyn regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Nisha V.', quote: 'Our office in Brooklyn has never looked better. Professional team, always on schedule.' },
  },
  'kingsville': {
    name: 'Kingsville',
    postcode: '3012',
    blurb: 'As a heritage suburb near Yarraville and Seddon, Kingsville is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Jayden R.', quote: 'The deep clean before we moved in was incredible — every room in our Kingsville home felt brand new.' },
  },
  'maidstone': {
    name: 'Maidstone',
    postcode: '3012',
    blurb: 'Maidstone is an established suburb near Highpoint Shopping Centre, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Maidstone properties.',
    testimonial: { name: 'Willow S.', quote: 'Our regular clean is spot-on every single time — Maidstone is lucky to have a team this reliable.' },
  },
  'west-footscray': {
    name: 'West Footscray',
    postcode: '3012',
    blurb: 'West Footscray is an established, multicultural suburb with its own train station. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout West Footscray, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Reza K.', quote: 'Our regular clean is spot-on every single time — West Footscray is lucky to have a team this reliable.' },
  },
  'gladstone-park': {
    name: 'Gladstone Park',
    postcode: '3043',
    blurb: 'Gladstone Park is a suburb centred around Gladstone Park Shopping Centre. Our fully insured team services Gladstone Park regularly, covering everything from routine home cleans to bond-back end of lease jobs.',
    testimonial: { name: 'Freya M.', quote: 'Our office in Gladstone Park has never looked better. Professional team, always on schedule.' },
  },
  'gowanbrae': {
    name: 'Gowanbrae',
    postcode: '3043',
    blurb: 'As a newer suburb near Gladstone Park built around a golf course community, Gowanbrae is one of the growing number of Western Melbourne suburbs we service directly from our Deanside base. Residential, commercial, end of lease and deep cleaning — all covered.',
    testimonial: { name: 'Oscar B.', quote: 'Our regular clean is spot-on every single time — Gowanbrae is lucky to have a team this reliable.' },
  },
  'tullamarine': {
    name: 'Tullamarine',
    postcode: '3043',
    blurb: 'Tullamarine is a suburb near Melbourne Airport and the Tullamarine Freeway, and it\'s part of our regular Western Melbourne coverage. Whether it\'s a weekly home clean or a full end of lease job, our team is fully insured and equipped for Tullamarine properties.',
    testimonial: { name: 'Layla H.', quote: 'Our office in Tullamarine has never looked better. Professional team, always on schedule.' },
  },
  'seabrook': {
    name: 'Seabrook',
    postcode: '3028',
    blurb: 'Seabrook is a residential suburb neighbouring Altona Meadows. UDAY Cleaning provides residential, commercial, end of lease and deep cleaning throughout Seabrook, with the same eco-friendly, fully insured service we bring to every job.',
    testimonial: { name: 'Tristan W.', quote: 'Our regular clean is spot-on every single time — Seabrook is lucky to have a team this reliable.' },
  },
}
